#ifndef HDTB_MACHINEMODULEDIRECTORY
#define HDTB_MACHINEMODULEDIRECTORY

#define HDTB_MACHINE_ADD 0
#define HDTB_MACHINE_EDIT 1
#define HDTB_MACHINE_REMOVE 2
#define HDTB_MACHINE_PERFORM 3
#define HDTB_MACHINE_GET 4
//#define HDTB_MACHINE_INSTALL 5

// Available sub-commands
#define HDTB_MACHINE_CMD_DOMAIN 0
#define HDTB_MACHINE_CMD_WORKGROUP 1
#define HDTB_MACHINE_CMD_ADMINISTRATOR 2
#define HDTB_MACHINE_CMD_UAC 3
#define HDTB_MACHINE_CMD_IE 4
#define HDTB_MACHINE_CMD_CNAME 5

#define HDTB_MACHINE_CMD_CLEANUP 5
#define HDTB_MACHINE_CMD_BACKUP 6

#define HDTB_MACHINE_CMD_RAM 7
#define HDTB_MACHINE_CMD_HDD 8
#define HDTB_MACHINE_CMD_CPU 9
#define HDTB_MACHINE_CMD_OS 10


#endif // HDTB_MACHINEMODULEDIRECTORY

