#ifndef HDTB_MACHINEMODULEDIRECTORY
#define HDTB_MACHINEMODULEDIRECTORY

// Sub module ids
#define HDTB_MACHINE_ADD 0
#define HDTB_MACHINE_EDIT 1
#define HDTB_MACHINE_REMOVE 2
#define HDTB_MACHINE_PERFORM 3
#define HDTB_MACHINE_GET 4

// Available sub-commands

// Add / Edit
#define HDTB_MACHINE_CMD_DOMAIN 0
#define HDTB_MACHINE_CMD_WORKGROUP 1
#define HDTB_MACHINE_CMD_ADMINISTRATOR 2
#define HDTB_MACHINE_CMD_UAC 3
#define HDTB_MACHINE_CMD_IE 4
// Edit
#define HDTB_MACHINE_CMD_CNAME 5
#define HDTB_MACHINE_CMD_UNAME 6
// Perform
#define HDTB_MACHINE_CMD_CLEANUP 7
#define HDTB_MACHINE_CMD_COPY 8
#define HDTB_MACHINE_CMD_WUPDATE 9
#define HDTB_MACHINE_CMD_SCRUB 10
// Get
#define HDTB_MACHINE_CMD_RAM 11
#define HDTB_MACHINE_CMD_HDD 12
#define HDTB_MACHINE_CMD_CPU 13
#define HDTB_MACHINE_CMD_OS 14

#endif // HDTB_MACHINEMODULEDIRECTORY

