#ifndef HDTB_SOFTWAREMODULEDIRECTORY
#define HDTB_SOFTWAREMODULEDIRECTORY

// Sub module ids
#define HDTB_SOFTWARE_INSTALL 0
#define HDTB_SOFTWARE_MODIFY 1
#define HDTB_SOFTWARE_REMOVE 2


// Software to Install
#define HDTB_SOFTWARE_CMD_INSTALL_JAVA 3
#define HDTB_SOFTWARE_CMD_INSTALL_KACE 4
#define HDTB_SOFTWARE_CMD_INSTALL_AVIRA 5

// Software to Modify
#define HDTB_SOFTWARE_CMD_MODIFY_JAVA 6
#define HDTB_SOFTWARE_CMD_MODIFY_IE 7

// Software to Remove

#define HDTB_SOFTWARE_CMD_REMOVE_JAVA 8
#define HDTB_SOFTWARE_CMD_REMOVE_KACE 9
#define HDTB_SOFTWARE_CMD_REMOVE_AVIRA 10



#endif // HDTB_SOFTWAREMODULEDIRECTORY
